In [2]:
import numpy as np
a= np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [15]:
import time
a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized calculation time = "+str(1000*(toc-tic)) + "ms")

c=0
tic = time.time()
for i in range(10000000):
    c+=a[i]*b[i]
toc = time.time()

print(c)
print("Normla calculation time = "+str(1000*(toc-tic)) + "ms")

2500415.5221025385
Vectorized calculation time = 6.924867630004883ms
2500415.5221027466
Normla calculation time = 1678.0807971954346ms


#### broadcasting

In [29]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print("A", A.shape, "\n",A, "\n")

cal = A.sum(axis=0) # sum vertically for horizontal use axis = 1
print("cal ",cal.shape, "\n", cal , "\n")

#broadcasting
# A is 3*4 dim, and cal is 1*4. so we can use only 100*(A/cal) using .reshape reassures us      
per = 100*(A/cal.reshape(1,4)) 
print("percentage ",per.shape, "\n", per , "\n")

A (3, 4) 
 [[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]] 

cal  (4,) 
 [ 59.  239.  155.4  76.9] 

percentage  (3, 4) 
 [[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]] 



These errors are to learn ! 

In [50]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c=a*b
print(c)
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [45]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)
c=a*b

In [49]:
a = np.random.randn(3,3)
b = np.random.randn(2,1)
c=a+b
c.shape

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [31]:
c

array([[-1.39561945,  0.26895105,  1.16629278],
       [ 1.83968735,  0.55559981,  1.15265102]])

In [36]:
a = np.array([[2,1],[1,3]])
c = np.dot(a,a)
c

array([[ 5,  5],
       [ 5, 10]])

In [40]:
x = np.random.randn(8,1)

In [42]:
x.reshape(2,2,2)

array([[[-0.21687289,  0.63108679],
        [-0.98769475,  1.45147055]],

       [[ 0.50549608,  0.58161685],
        [ 1.35296657, -0.40214051]]])

In [52]:
a = np.array([[1,1],[1,-1]])
b = np.array([[2],[3]])
c = a+b
c

array([[3, 3],
       [4, 2]])

<img href="https://www.google.co.in/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F9%2F99%2FNeural_network_example.svg%2F1200px-Neural_network_example.svg.png&tbnid=WGaLD4eL1CCBwM&vet=12ahUKEwiU176AkrSDAxWBxskDHQpBAL8QMygAegQIARBd..i&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FNeural_network&docid=4uDq4ZiJWlnL0M&w=1200&h=1600&q=basic%20neural%20network&client=safari&ved=2ahUKEwiU176AkrSDAxWBxskDHQpBAL8QMygAegQIARBd">

In [57]:
x = np.random.rand(3, 2)

y = np.sum(x, axis=0, keepdims=True)
y.shape

(1, 2)

In [58]:
A = np.random.randn(4,3)

B = np.sum(A, axis = 1, keepdims = True) 

In [59]:
B.shape

(4, 1)